{% set name = "setuptools-rust" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools-rust/setuptools-rust-{{ version }}.tar.gz
  sha256: a0adb9b503c0ffc4e8fe80b7c617898cefa78049983aaaea7f747e153a3e65d1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=46.1
    - setuptools_scm >=3.4.3
  run:
    - python >=3.6
    - semantic_version >=2.8.2
    - setuptools >=46.1
    - tomli >=1.2.1
    - typing_extensions >=3.7.4.3

test:
  imports:
    - setuptools_rust
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyO3/setuptools-rust
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Setuptools rust extension plugin

extra:
  recipe-maintainers:
    - davidhewitt
    - nicoddemus
