{% set version = "1.8.0" %}

package:
  name: setuptools-rust
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools-rust/setuptools-rust-{{ version }}.tar.gz
  sha256: 5e02b7a80058853bf64127314f6b97d0efed11e08b94c88ca639a20976f6adc4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=62.4
  run:
    - python >=3.8
    - semantic_version >=2.8.2,<3
    - setuptools >=62.4
    - tomli >=1.2.1

test:
  imports:
    - setuptools_rust
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyO3/setuptools-rust
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Setuptools rust extension plugin

extra:
  recipe-maintainers:
    - davidhewitt
    - nicoddemus
