{% set version = "1.10.2" %}

package:
  name: setuptools-rust
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/setuptools-rust/setuptools_rust-{{ version }}.tar.gz
  sha256: 5d73e7eee5f87a6417285b617c97088a7c20d1a70fcea60e3bdc94ff567c29dc

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=62.4
  run:
    - python >={{ python_min }}
    - semantic_version >=2.8.2,<3
    - setuptools >=62.4

test:
  imports:
    - setuptools_rust
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PyO3/setuptools-rust
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Setuptools rust extension plugin

extra:
  recipe-maintainers:
    - davidhewitt
    - nicoddemus
