{% set version = "1.10.1" %}

package:
  name: setuptools-rust
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools-rust/setuptools_rust-{{ version }}.tar.gz
  sha256: d79035fc54cdf9342e9edf4b009491ecab06c3a652b37c3c137c7ba85547d3e6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=62.4
  run:
    - python >=3.8
    - semantic_version >=2.8.2,<3
    - setuptools >=62.4

test:
  imports:
    - setuptools_rust
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyO3/setuptools-rust
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Setuptools rust extension plugin

extra:
  recipe-maintainers:
    - davidhewitt
    - nicoddemus
