{% set name = "setuptools-rust" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setuptools-rust/setuptools-rust-{{ version }}.tar.gz
  sha256: faacca4b85d5f43e9e3836418e1cbf9ed2576a27978b522f3d04513ef052cec5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=41
    - setuptools_scm >=3.4.3
  run:
    - python >=3.5
    - semantic_version >=2.6.0
    - setuptools >=41
    - toml >=0.9.0

test:
  imports:
    - setuptools_rust
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyO3/setuptools-rust
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Setuptools rust extension plugin

extra:
  recipe-maintainers:
    - nicoddemus
